services:
  # Use root/example as user/password credentials here
  mongodb:
    image: mongo:5.0-rc-focal
    restart: always
    ports:
      - 27017:27017 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

  # temporary so we can import the db and have access to console
  mongo-seed:
    image: mongo:5.0-rc-focal
    links:
      - mongodb
    volumes:
      - ./db_dumps:/db_dumps
    entrypoint: /bin/bash
